import { DecodeFieldType } from '../../types/decoder'
import type { DecodeMode } from '../../types/decoder'

export const mMode: DecodeMode[] = [
  // 0x300 - mstatus
  {
    name: 'mstatus',
    fields: [
      { low: 0, type: DecodeFieldType.CSR_WPRI },
      { low: 1, name: 'SIE', description: 'Supervisor Interrupt Enable' },
      { low: 2, type: DecodeFieldType.CSR_WPRI },
      { low: 3, name: 'MIE', description: 'Machine Interrupt Enable' },
      { low: 4, type: DecodeFieldType.CSR_WPRI },
      { low: 5, name: 'SPIE', description: 'Supervisor Previous Interrupt Enable' },
      { low: 6, name: 'UBE', description: 'User Big Endian' },
      { low: 7, name: 'MPIE', description: 'Machine Previous Interrupt Enable' },
      { low: 8, name: 'SPP', description: 'Supervisor Previous Privilege', value: ['U', 'VS'] },
      {
        low: 9,
        high: 10,
        name: 'VS',
        description: 'Vector State',
        value: ['Off', 'Initial', 'Clean', 'Dirty'],
      },
      {
        low: 11,
        high: 12,
        name: 'MPP',
        description: 'Machine Previous Privilege',
        value: ['U', 'VS', 'HS', 'M'],
      },
      {
        low: 13,
        high: 14,
        name: 'FS',
        description: 'Floating-point State',
        value: ['Off', 'Initial', 'Clean', 'Dirty'],
      },
      {
        low: 15,
        high: 16,
        name: 'XS',
        description: 'Extended State',
        value: ['Off', 'Initial', 'Clean', 'Dirty'],
      },
      { low: 17, name: 'MPRV', description: 'Modify Privilege' },
      { low: 18, name: 'SUM', description: 'Supervisor can access User Memory' },
      { low: 19, name: 'MXR', description: 'Machine eXecutable Read' },
      { low: 20, name: 'TVM', description: 'Trap Virtual Memory' },
      { low: 21, name: 'TW', description: 'Timeout Wait' },
      { low: 22, name: 'TSR', description: 'Trap SRET' },
      { low: 23, name: 'SPELP', description: 'Supervisor Previous Expected Landing Pad' },
      { low: 24, name: 'SDT', description: 'Supervisor Disable Trap' },
      { low: 25, high: 31, type: DecodeFieldType.CSR_WPRI },
      {
        low: 32,
        high: 33,
        name: 'UXL',
        description: 'User XLEN',
        value: ['Not supported', '32', '64', 'Reserved'],
      },
      {
        low: 34,
        high: 35,
        name: 'SXL',
        description: 'Supervisor XLEN',
        value: ['Not supported', '32', '64', 'Reserved'],
      },
      {
        low: 36,
        name: 'SBE',
        description: 'Supervisor Byte Endian',
        value: ['Little endian', 'Big endian'],
      },
      {
        low: 37,
        name: 'MBE',
        description: 'Machine Byte Endian',
        value: ['Little endian', 'Big endian'],
      },
      { low: 38, name: 'GVA', description: 'Guest Virtual Address' },
      { low: 39, name: 'MPV', description: 'Machine Previous Virtualization Mode' },
      { low: 40, type: DecodeFieldType.CSR_WPRI },
      { low: 41, name: 'MPELP', description: 'Machine Previous Expected Landing Pad' },
      { low: 42, name: 'MDT', description: 'Machine Disable Trap' },
      { low: 43, high: 62, type: DecodeFieldType.CSR_WPRI },
      { low: 63, name: 'SD', description: 'Some Dirty (VS/FS/XS dirty)' },
    ],
  },
  // 0x301 - misa
  {
    name: 'misa',
    fields: [
      { low: 0, name: 'A' },
      { low: 1, name: 'B' },
      { low: 2, name: 'C' },
      { low: 3, name: 'D' },
      { low: 4, name: 'E' },
      { low: 5, name: 'F' },
      { low: 6, name: 'G' },
      { low: 7, name: 'H' },
      { low: 8, name: 'I' },
      { low: 9, name: 'J' },
      { low: 10, name: 'K' },
      { low: 11, name: 'L' },
      { low: 12, name: 'M' },
      { low: 13, name: 'N' },
      { low: 14, name: 'O' },
      { low: 15, name: 'P' },
      { low: 16, name: 'Q' },
      { low: 17, name: 'R' },
      { low: 18, name: 'S' },
      { low: 19, name: 'T' },
      { low: 20, name: 'U' },
      { low: 21, name: 'V' },
      { low: 22, name: 'W' },
      { low: 23, name: 'X' },
      { low: 24, name: 'Y' },
      { low: 25, name: 'Z' },
      { low: 26, high: 61, type: DecodeFieldType.CSR_RO0 },
      {
        low: 62,
        high: 63,
        name: 'MXL',
        description: 'Machine XLEN',
        value: ['Not supported', '32', '64', 'Reserved'],
      },
    ],
  },
  // 0x302 - medeleg
  {
    name: 'medeleg',
    fields: [
      { low: 0, name: 'IAM', description: 'Instruction Address Misaligned' },
      { low: 1, name: 'IAF', description: 'Instruction Access Fault' },
      { low: 2, name: 'II', description: 'Illegal Instruction' },
      { low: 3, name: 'B', description: 'Breakpoint' },
      { low: 4, name: 'LAM', description: 'Load Address Misaligned' },
      { low: 5, name: 'LAF', description: 'Load Access Fault' },
      { low: 6, name: 'SAM', description: 'Store/AMO Address Misaligned' },
      { low: 7, name: 'SAF', description: 'Store/AMO Access Fault' },
      { low: 8, name: 'EU', description: 'Environment call from U-mode or VU-mode' },
      { low: 9, name: 'EVS', description: 'Environment call from VS-mode' },
      {
        low: 10,
        name: 'EM',
        description: 'Environment call from M-mode',
        type: DecodeFieldType.CSR_RO0,
      },
      { low: 11, name: 'IPF', description: 'Instruction Page Fault' },
      { low: 12, name: 'LPF', description: 'Load Page Fault' },
      { low: 13, type: DecodeFieldType.CSR_RO0 },
      { low: 14, name: 'SPF', description: 'Store/AMO Page Fault' },
      { low: 15, name: 'DT', description: 'Double Trap' },
      { low: 16, type: DecodeFieldType.CSR_RO0 },
      { low: 17, name: 'SC', description: 'Software Check' },
      { low: 18, name: 'HE', description: 'Hardware Error' },
      { low: 19, name: 'IGPF', description: 'Instruction Guest Page Fault' },
      { low: 20, name: 'LGPF', description: 'Load Guest Page Fault' },
      { low: 21, name: 'VI', description: 'Virtual Instruction' },
      { low: 22, name: 'SGPF', description: 'Store/AMO Guest Page Fault' },
      { low: 23, high: 62, type: DecodeFieldType.CSR_RO0 },
      { low: 63, type: DecodeFieldType.CSR_RO0 },
    ],
  },
  // 0x303 - mideleg
  {
    name: 'mideleg',
    fields: [
      { low: 0, type: DecodeFieldType.CSR_RO0 },
      { low: 1, name: 'SSIP', description: 'Supervisor Software Interrupt Pending' },
      { low: 2, name: 'VSSIP', description: 'Virtual Supervisor Software Interrupt Pending' },
      { low: 3, name: 'MSIP', description: 'Machine Software Interrupt Pending' },
      { low: 4, type: DecodeFieldType.CSR_RO0 },
      { low: 5, name: 'STIP', description: 'Supervisor Timer Interrupt Pending' },
      { low: 6, name: 'VSTIP', description: 'Virtual Supervisor Timer Interrupt Pending' },
      { low: 7, name: 'MTIP', description: 'Machine Timer Interrupt Pending' },
      { low: 8, type: DecodeFieldType.CSR_RO0 },
      { low: 9, name: 'SEIP', description: 'Supervisor External Interrupt Pending' },
      { low: 10, name: 'VSEIP', description: 'Virtual Supervisor External Interrupt Pending' },
      { low: 11, name: 'MEIP', description: 'Machine External Interrupt Pending' },
      { low: 12, name: 'SGEIP', description: 'Supervisor Guest External Interrupt Pending' },
      { low: 13, name: 'LCOFIP', description: 'Local Counter OverFlow Interrupt Pending' },
      { low: 14, high: 15, type: DecodeFieldType.CSR_RO0 },
      { low: 16, high: 63, type: DecodeFieldType.CSR_WPRI },
    ],
  },
  // 0x304 - mie
  {
    name: 'mie',
    fields: [
      { low: 0, type: DecodeFieldType.CSR_RO0 },
      { low: 1, name: 'SSIE', description: 'Supervisor Software Interrupt Enable' },
      { low: 2, name: 'VSSIE', description: 'Virtual Supervisor Software Interrupt Enable' },
      { low: 3, name: 'MSIE', description: 'Machine Software Interrupt Enable' },
      { low: 4, type: DecodeFieldType.CSR_RO0 },
      { low: 5, name: 'STIE', description: 'Supervisor Timer Interrupt Enable' },
      { low: 6, name: 'VSTIE', description: 'Virtual Supervisor Timer Interrupt Enable' },
      { low: 7, name: 'MTIE', description: 'Machine Timer Interrupt Enable' },
      { low: 8, type: DecodeFieldType.CSR_RO0 },
      { low: 9, name: 'SEIE', description: 'Supervisor External Interrupt Enable' },
      { low: 10, name: 'VSEIE', description: 'Virtual Supervisor External Interrupt Enable' },
      { low: 11, name: 'MEIE', description: 'Machine External Interrupt Enable' },
      { low: 12, name: 'SGEIE', description: 'Supervisor Guest External Interrupt Enable' },
      { low: 13, name: 'LCOFIE', description: 'Local Counter OverFlow Interrupt Enable' },
      { low: 14, high: 15, type: DecodeFieldType.CSR_RO0 },
      { low: 16, high: 63, type: DecodeFieldType.CSR_WPRI },
    ],
  },
  // 0x305 - mtvec
  {
    name: 'mtvec',
    fields: [
      { low: 0, high: 1, name: 'MODE', value: ['Direct', 'Vectored', 'Reserved', 'Reserved'] },
      { low: 2, high: 63, name: 'BASE' },
    ],
  },
  // 0x306 - mcounteren
  {
    name: 'mcounteren',
    fields: [
      { low: 0, name: 'CY' },
      { low: 1, name: 'TM' },
      { low: 2, name: 'IR' },
      { low: 3, high: 31, name: 'HPM[31:3]' },
      { low: 32, high: 63, type: DecodeFieldType.CSR_RO0 },
    ],
  },
  // 0x30A - menvcfg
  {
    name: 'menvcfg',
    fields: [
      { low: 0, name: 'FIOM' },
      { low: 1, type: DecodeFieldType.CSR_WPRI },
      { low: 2, name: 'LPE' },
      { low: 3, name: 'SSE' },
      { low: 4, high: 5, name: 'CBIE', value: ['Invalid', 'Flush', 'Invalidate', 'Reserved'] },
      { low: 6, name: 'CBCFE' },
      { low: 7, name: 'CBZE' },
      { low: 8, high: 31, type: DecodeFieldType.CSR_WPRI },
      { low: 32, high: 33, name: 'PMM' },
      { low: 34, high: 58, type: DecodeFieldType.CSR_WPRI },
      { low: 59, name: 'DTE' },
      { low: 60, name: 'CDE' },
      { low: 61, name: 'ADUE' },
      { low: 62, name: 'PBMTE' },
      { low: 63, name: 'STCE' },
    ],
  },
  // 0x30C - mstateen0
  {
    name: 'mstateen0',
    fields: [
      { low: 0, name: 'C' },
      { low: 1, name: 'FCSR' },
      { low: 2, name: 'JVT' },
      { low: 3, high: 53, type: DecodeFieldType.CSR_WPRI },
      { low: 54, name: 'CTR' },
      { low: 55, name: 'SRMCFG' },
      { low: 56, name: 'P1P13' },
      { low: 57, name: 'CONTEXT' },
      { low: 58, name: 'IMISC' },
      { low: 59, name: 'AIA' },
      { low: 60, name: 'CSRIND' },
      { low: 61, type: DecodeFieldType.CSR_WPRI },
      { low: 62, name: 'ENVCFG' },
      { low: 63, name: 'SE0' },
    ],
  },
  // 0x320 - mcountinhibit
  {
    name: 'mcountinhibit',
    fields: [
      { low: 0, name: 'CY' },
      { low: 1, type: DecodeFieldType.CSR_RO0 },
      { low: 2, name: 'IR' },
      { low: 3, high: 31, name: 'HPM[31:3]' },
      { low: 32, high: 63, type: DecodeFieldType.CSR_RO0 },
    ],
  },
  // 0x321 - mcyclecfg
  {
    name: 'mcyclecfg',
    fields: [
      { low: 0, high: 57, type: DecodeFieldType.CSR_WPRI },
      { low: 58, name: 'VUINH' },
      { low: 59, name: 'VSINH' },
      { low: 60, name: 'UINH' },
      { low: 61, name: 'SINH' },
      { low: 62, name: 'MINH' },
      { low: 63, type: DecodeFieldType.CSR_RO0 },
    ],
  },
  // 0x340 - mscratch
  {
    name: 'mscratch',
    fields: [{ low: 0, high: 63, name: 'VALUE' }],
  },
  // 0x341 - mepc
  {
    name: 'mepc',
    fields: [
      { low: 0, type: DecodeFieldType.CSR_RO0 },
      { low: 1, name: 'PC[1]' },
      { low: 2, high: 63, name: 'PC[63:2]' },
    ],
  },
  // 0x342 - mcause
  {
    name: 'mcause',
    fields: [
      {
        name: 'Exception',
        condition: { field: 'INTR', value: BigInt(0) },
        fields: [
          {
            low: 0,
            high: 62,
            name: 'Exception Code',
            value: new Map<bigint, string>([
              [BigInt(0x0), 'Instruction address misaligned'],
              [BigInt(0x1), 'Instruction access fault'],
              [BigInt(0x2), 'Illegal instruction'],
              [BigInt(0x3), 'Breakpoint'],
              [BigInt(0x4), 'Load address misaligned'],
              [BigInt(0x5), 'Load access fault'],
              [BigInt(0x6), 'Store/AMO address misaligned'],
              [BigInt(0x7), 'Store/AMO access fault'],
              [BigInt(0x8), 'Environment call from U-mode or VU-mode'],
              [BigInt(0x9), 'Environment call from HS-mode'],
              [BigInt(0xa), 'Environment call from VS-mode'],
              [BigInt(0xb), 'Environment call from M-mode'],
              [BigInt(0xc), 'Instruction page fault'],
              [BigInt(0xd), 'Load page fault'],
              [BigInt(0xf), 'Store/AMO page fault'],
              [BigInt(0x10), 'Double trap'],
              [BigInt(0x12), 'Software check'],
              [BigInt(0x13), 'Hardware error'],
              [BigInt(0x14), 'Instruction guest-page fault'],
              [BigInt(0x15), 'Load guest-page fault'],
              [BigInt(0x16), 'Virtual instruction'],
              [BigInt(0x17), 'Store/AMO guest-page fault'],
              [BigInt(0x18), 'Custom exception'],
              [BigInt(0x19), 'Custom exception'],
              [BigInt(0x1a), 'Custom exception'],
              [BigInt(0x1b), 'Custom exception'],
              [BigInt(0x1c), 'Custom exception'],
              [BigInt(0x1d), 'Custom exception'],
              [BigInt(0x1e), 'Custom exception'],
              [BigInt(0x1f), 'Custom exception'],
              [BigInt(0x30), 'Custom exception'],
              [BigInt(0x31), 'Custom exception'],
              [BigInt(0x32), 'Custom exception'],
              [BigInt(0x33), 'Custom exception'],
              [BigInt(0x34), 'Custom exception'],
              [BigInt(0x35), 'Custom exception'],
              [BigInt(0x36), 'Custom exception'],
              [BigInt(0x37), 'Custom exception'],
              [BigInt(0x38), 'Custom exception'],
              [BigInt(0x39), 'Custom exception'],
              [BigInt(0x3a), 'Custom exception'],
              [BigInt(0x3b), 'Custom exception'],
              [BigInt(0x3c), 'Custom exception'],
              [BigInt(0x3d), 'Custom exception'],
              [BigInt(0x3e), 'Custom exception'],
              [BigInt(0x3f), 'Custom exception'],
            ]),
          },
        ],
      },
      {
        name: 'Interrupt',
        condition: { field: 'INTR', value: BigInt(1) },
        fields: [
          {
            low: 0,
            high: 62,
            name: 'Interrupt Code',
            value: new Map<bigint, string>([
              [BigInt(0x1), 'Supervisor software interrupt'],
              [BigInt(0x2), 'Virtual supervisor software interrupt'],
              [BigInt(0x3), 'Machine software interrupt'],
              [BigInt(0x5), 'Supervisor timer interrupt'],
              [BigInt(0x6), 'Virtual supervisor timer interrupt'],
              [BigInt(0x7), 'Machine timer interrupt'],
              [BigInt(0x9), 'Supervisor external interrupt'],
              [BigInt(0xa), 'Virtual supervisor external interrupt'],
              [BigInt(0xb), 'Machine external interrupt'],
              [BigInt(0xc), 'Supervisor guest external interrupt'],
              [BigInt(0xd), 'Reserved for counter-overflow interrupt'],
            ]),
          },
        ],
      },
      { low: 63, name: 'INTR' },
    ],
  },
  // 0x343 - mtval
  {
    name: 'mtval',
    fields: [{ low: 0, high: 63, name: 'VALUE' }],
  },
  // 0x344 - mip
  {
    name: 'mip',
    fields: [
      { low: 0, type: DecodeFieldType.CSR_RO0 },
      { low: 1, name: 'SSIP', description: 'Supervisor Software Interrupt Pending' },
      { low: 2, name: 'VSSIP', description: 'Virtual Supervisor Software Interrupt Pending' },
      { low: 3, name: 'MSIP', description: 'Machine Software Interrupt Pending' },
      { low: 4, type: DecodeFieldType.CSR_RO0 },
      { low: 5, name: 'STIP', description: 'Supervisor Timer Interrupt Pending' },
      { low: 6, name: 'VSTIP', description: 'Virtual Supervisor Timer Interrupt Pending' },
      { low: 7, name: 'MTIP', description: 'Machine Timer Interrupt Pending' },
      { low: 8, type: DecodeFieldType.CSR_RO0 },
      { low: 9, name: 'SEIP', description: 'Supervisor External Interrupt Pending' },
      { low: 10, name: 'VSEIP', description: 'Virtual Supervisor External Interrupt Pending' },
      { low: 11, name: 'MEIP', description: 'Machine External Interrupt Pending' },
      { low: 12, name: 'SGEIP', description: 'Supervisor Guest External Interrupt Pending' },
      { low: 13, name: 'LCOFIP', description: 'Local Counter Overflow Interrupt Pending' },
      { low: 14, high: 15, type: DecodeFieldType.CSR_RO0 },
      { low: 16, high: 63, type: DecodeFieldType.CSR_WPRI },
    ],
  },
  // 0x3A0 - pmpcfg0
  {
    name: 'pmpcfg0',
    fields: [
      { low: 0, name: '0.R' },
      { low: 1, name: '0.W' },
      { low: 2, name: '0.X' },
      { low: 3, high: 4, name: '0.A', value: ['OFF', 'TOR', 'NA4', 'NAPOT'] },
      { low: 5, high: 6, type: DecodeFieldType.CSR_RO0 },
      { low: 7, name: '0.L' },
      { low: 8, name: '1.R' },
      { low: 9, name: '1.W' },
      { low: 10, name: '1.X' },
      { low: 11, high: 12, name: '1.A', value: ['OFF', 'TOR', 'NA4', 'NAPOT'] },
      { low: 13, high: 14, type: DecodeFieldType.CSR_RO0 },
      { low: 15, name: '1.L' },
      { low: 16, name: '2.R' },
      { low: 17, name: '2.W' },
      { low: 18, name: '2.X' },
      { low: 19, high: 20, name: '2.A', value: ['OFF', 'TOR', 'NA4', 'NAPOT'] },
      { low: 21, high: 22, type: DecodeFieldType.CSR_RO0 },
      { low: 23, name: '2.L' },
      { low: 24, name: '3.R' },
      { low: 25, name: '3.W' },
      { low: 26, name: '3.X' },
      { low: 27, high: 28, name: '3.A', value: ['OFF', 'TOR', 'NA4', 'NAPOT'] },
      { low: 29, high: 30, type: DecodeFieldType.CSR_RO0 },
      { low: 31, name: '3.L' },
      { low: 32, name: '4.R' },
      { low: 33, name: '4.W' },
      { low: 34, name: '4.X' },
      { low: 35, high: 36, name: '4.A', value: ['OFF', 'TOR', 'NA4', 'NAPOT'] },
      { low: 37, high: 38, type: DecodeFieldType.CSR_RO0 },
      { low: 39, name: '4.L' },
      { low: 40, name: '5.R' },
      { low: 41, name: '5.W' },
      { low: 42, name: '5.X' },
      { low: 43, high: 44, name: '5.A', value: ['OFF', 'TOR', 'NA4', 'NAPOT'] },
      { low: 45, high: 46, type: DecodeFieldType.CSR_RO0 },
      { low: 47, name: '5.L' },
      { low: 48, name: '6.R' },
      { low: 49, name: '6.W' },
      { low: 50, name: '6.X' },
      { low: 51, high: 52, name: '6.A', value: ['OFF', 'TOR', 'NA4', 'NAPOT'] },
      { low: 53, high: 54, type: DecodeFieldType.CSR_RO0 },
      { low: 55, name: '6.L' },
      { low: 56, name: '7.R' },
      { low: 57, name: '7.W' },
      { low: 58, name: '7.X' },
      { low: 59, high: 60, name: '7.A', value: ['OFF', 'TOR', 'NA4', 'NAPOT'] },
      { low: 61, high: 62, type: DecodeFieldType.CSR_RO0 },
      { low: 63, name: '7.L' },
    ],
  },
  // 0x3B0 - pmpaddr0
  {
    name: 'pmpaddr0',
    fields: [
      { low: 0, high: 53, name: 'ADDRESS' },
      { low: 54, high: 63, type: DecodeFieldType.CSR_RO0 },
    ],
  },
  // 0x747 - mseccfg
  {
    name: 'mseccfg',
    fields: [
      { low: 0, name: 'MML' },
      { low: 1, name: 'MMWP' },
      { low: 2, name: 'RLB' },
      { low: 3, high: 7, type: DecodeFieldType.CSR_WPRI },
      { low: 8, name: 'USEED' },
      { low: 9, name: 'SSEED' },
      { low: 10, name: 'MLPE' },
      { low: 11, high: 31, type: DecodeFieldType.CSR_WPRI },
      { low: 32, high: 33, name: 'PMM' },
      { low: 34, high: 63, type: DecodeFieldType.CSR_WPRI },
    ],
  },
]
